block_args:
  dim_feedforward: 32
  enable_layer_norm: true
  input_dim: 16
  num_heads: 4
  num_layers: 2
block_input_dim: 16
dropout: 0.0
input_dim: 2
learning_rate: 0.1
num_layers: 2
positional_encoder_args:
  enable: false
  max_len: 8
