SOURCES = linear_transformer_tb.cpp linear_transformer.cpp linear_transformer.h scaled_dp_params.h
a.out: $(SOURCES)
	# g++ -g -Wall -fpermissive $(SOURCES)
	g++ -g -Wall -Wno-unused-label -Wno-unknown-pragmas -fpermissive $(SOURCES)